apiVersion: v2
name: kz-scoring-api
description: |
  Synchronous REST facade for Beeline-initiator PKB lookups via vaultee-pipelines.
type: application
version: 0.1.1
appVersion: "0.1.1"
maintainers:
  - name: Aggregion
