{{- if .Values.apiToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kz-scoring-api.fullname" . }}-token
  labels:
    {{- include "kz-scoring-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  KZ_SCORING_API_TOKEN: {{ .Values.apiToken | quote }}
{{- end }}
